[package]
name = "quiet-stroll"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwalk = "0.5"
serde_json = "1.0.91"
glob = "0.3.1"
schemars = "0.7"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]

[dependencies.rocket_okapi]
features = ["swagger"]
